[package]
name = "griffel_experiments"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib"]

[dependencies]
fasthash = "0.4.0"
js-sys = "0.3.69"
murmur2 = "0.1.0"
radix_fmt = "1.0.0"
wasm-bindgen = "0.2.92"
