[package]
name = "wasm-hash"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
debug = false
opt-level = 3
target = "wasm32-unknown-unknown"
strip = true
