[target.wasm32-unknown-unknown]
rustflags = [
  "-C",
  "link-args=--import-memory",
  "-C",
  "link-arg=--initial-memory=65536",
  "-C",
  "link-arg=--max-memory=65536",
  "-C",
  "link-arg=-zstack-size=0",
]
